### ISSUE TITLE
Connecting to my Sql Server 

### ISSUE THREAD

**Issue by Jazhan** [SIU-CS/Direct_Democracy-production#16]
Currently working on connecting to My Sql Data Base server. resovling security issues....

E: Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/main/libh/libhtml-template-perl/libhtml-template-perl_2.95-1_all.deb  Could not resolve 'us.archive.ubuntu.com'

E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/m/mysql-5.5/mysql-server_5.5.54-0ubuntu0.14.04.1_all.deb  Could not resolve 'security.ubuntu.com'

**Comment by GregoryBrinkman** [comment]
Here's an article about this.
https://support.rackspace.com/how-to/installing-mysql-server-on-ubuntu/

**Comment by GregoryBrinkman** [comment]
Connecting a node.js server to couchDB instead.
https://couchdb.apache.org/

**Comment by akohli96** [comment]
@Jazhan  http://askubuntu.com/questions/687811/cant-install-mysql-on-ubuntu
